HTTP/1.1 200 OK
Server: Cowboy
Connection: close
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 92
Etag: W/"5c-0uazLUgawm3yGZMFumvnOqOj3Bc"
Date: Fri, 10 Jun 2022 00:07:12 GMT
Via: 1.1 vegur

{"msg":"post API - Controller","data":{"name":"John Doe","email":"johndoe@johndoemail.com"}}